# Generated by Django 4.2.4 on 2023-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
